<a href="https://colab.research.google.com/github/jacksonsin/Practical-Statistics-for-Data-Scientists/blob/main/Import_CSV_file_to_Colab_VM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Method 1

In [1]:
# Read csv file from Github 
import requests
url = 'https://raw.githubusercontent.com/jacksonsin/datasets/main/items.csv'
page = requests.get(url)
print(page.text)

name,price,quantity
Phone,100,1
Laptop,1000,3
Cable,10,5
Mouse,50,5
Keyboard,74.9,5

In [2]:
# Save a copy of csv file as items.csv in Colab VM
import os
with open(os.getcwd()+'/items.csv', "w") as myfile:
    myfile.write(page.text)

In [3]:
# Read the csv file from Colab VM
import pandas as pd
df = pd.read_csv('items.csv')
df

       name   price  quantity
0     Phone   100.0         1
1    Laptop  1000.0         3
2     Cable    10.0         5
3     Mouse    50.0         5
4  Keyboard    74.9         5

Method 2

In [54]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/jacksonsin/datasets/main/items.csv')
df.head()

       name   price  quantity
0     Phone   100.0         1
1    Laptop  1000.0         3
2     Cable    10.0         5
3     Mouse    50.0         5
4  Keyboard    74.9         5